### ISSUE TITLE
Making a shard out of it

### ISSUE THREAD

**Issue by Heaven31415** [BlaXpirit/crystal-raw-gl#3]
Hi, I like this raw binding to gl and glu, however I'm thinking that it would be much nicer to make a shard out of it.

- You wouldn't have to copy and paste big inconvenient files.
- You could be sure you have the most updated code in case something changes.
- You could use it as a dependency for another library.

What do you think? In case you agree, but you don't have time or will to do it, I think I can provide appropriate PR.

**Comment by oprypin** [comment]
But it works as a shard, you can do this:

```yaml
dependencies:
  gl:
    github: oprypin/crystal-raw-gl
```

**Comment by Heaven31415** [comment]
Thanks for quick response. I just tested it and it works, however you don't get any information about version, which looks weird. Would you mind adding _shard.yml_ file to make it work?
